baseurl: "" # the subpath of your site, e.g. /blog
title: Savan # the name of your site, e.g. ACME Corp.
author: SavanDev

source: website

permalink: /:categories/:year/:title/

exclude:
  - "webpack.config.js"
  
include:
  - ".well-known"
  - ".nojekyll"

js_dest: /assets/js

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-youtube

# SEO
twitter:
  username: dylnavas36
  card: summary
tagline: "Welcome, I'm Savan!"
url: https://savandev.ar
social:
  name: SavanDev
  links:
    - https://twitter.com/dylnavas36
    - https://github.com/SavanDev
logo: /assets/img/logo-back.png
github: SavanDev
