baseurl: "" # the subpath of your site, e.g. /blog
title: SavanDev # the name of your site, e.g. ACME Corp.
author: SavanDev

source: portfolio
showNavbar: 1

permalink: /:categories/:year/:title/

exclude:
  - "webpack.config.js"

js_dest: /assets/js

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-youtube

# SEO
twitter:
  username: dylnavas36
  card: summary
tagline: "SavanDev - My portfolio"
url: https://savandev.github.io
social:
  name: Dylan Navas
  links:
    - https://twitter.com/dylnavas36
    - https://github.com/SavanDev
    - https://www.instagram.com/savan_7870/
logo: /assets/img/logo.png
github: SavanDev
instagram: savan_7870